### ISSUE TITLE
Other scripts are not loading in Inner Page 

### ISSUE THREAD

**Issue by rhenryrobert** [appleple/lookforward#7]
Hi,
For example, Landing page in "a", Navigating to Page "B". Page "B" have slider & form validation. Without lookforward.Js slider script and other scripts are working fine. If I add lookforward.Js.. other jQuery scripts are not loading.. How to fix that ?

**Comment by steelydylan** [comment]
Hi @rhenryrobert 
yeah.. That's what I have to solve
For now, you may want to call event listeners like below

```js
var lookforward = new LookForward('js-lookforward');
lookforward.on('open', function(){
    if (location.href === 'page_b.html'){
        // write code here
    }
});
```

**Comment by rhenryrobert** [comment]
@steelydylan 

Its not working. "Open" callback fn itself not triggered

**Comment by steelydylan** [comment]
@rhenryrobert 

I think It's because of the version
You may want to check this html for the reference
https://github.com/appleple/lookforward/blob/master/test/index.html

**Comment by rhenryrobert** [comment]
@steelydylan 

I checked this file also. Close & Close all is working, Open is not triggering.

**Comment by rhenryrobert** [comment]
Please check this screenshot..

![screen shot 2017-09-12 at 10 32 12 am](https://user-images.githubusercontent.com/7262633/30308872-b95962a0-97a5-11e7-8cc2-bbd2105e79a2.png)

**Comment by steelydylan** [comment]
@rhenryrobert 

I added 'open' event quite recently, so please download lookforward again and check if it works

**Comment by steelydylan** [comment]
Hi @rhenryrobert 

I just added the option 'execInnerScript' so to execute scripts inside fetched documents
see https://github.com/appleple/lookforward#tips

you can use this option from v.1.0.1

**Comment by rhenryrobert** [comment]
Awesome buddy... Let me check.

**Comment by rhenryrobert** [comment]
@steelydylan 

Is it possible to target all "a" tag instead of class selector
